import { describe, expect, it } from 'vitest'; import { createAnalyticsRegistry } from '../domain.mjs';
const engineer = { id: 'engineer-1', role: 'analytics-engineer' }; const governor = { id: 'governor-1', role: 'query-governor' }; const operator = { id: 'operator-1', role: 'analytics-operator' };
const input = { id: 'VIEW-352', supplier: 'Nexus Supplier Partners', dataset: 'supplier_intelligence', viewName: 'supplier_risk_summary', metrics: ['riskScore', 'deliveryVariance'] };
const codeOf = task => { try { task(); } catch (error) { return error.code; } };
describe('supplier analytics governance', () => {
  it('defines, reviews, publishes, revokes, and audits an analytics view', () => { const registry = createAnalyticsRegistry(); expect(registry.define(engineer, input).state).toBe('defined'); expect(registry.review(governor, input.id, 'Query review confirms metric provenance, field restrictions, query costs, and consumer access limits.').state).toBe('reviewed'); expect(registry.publish(operator, input.id).state).toBe('published'); expect(registry.revoke(operator, input.id, 'Metric provenance changed.').state).toBe('revoked'); expect(registry.audit()).toHaveLength(4); });
  it('rejects malformed and duplicate analytics views', () => { const registry = createAnalyticsRegistry(); expect(codeOf(() => registry.define(engineer, { ...input, id: 'bad', metrics: [] }))).toBe('VALIDATION'); registry.define(engineer, input); expect(codeOf(() => registry.define(engineer, input))).toBe('CONFLICT'); });
  it('enforces authorization, missing views, evidence, and publication gates', () => { const registry = createAnalyticsRegistry(); registry.define(engineer, input); expect(codeOf(() => registry.review(engineer, input.id, 'Query review confirms metric provenance, field restrictions, query costs, and consumer access limits.'))).toBe('FORBIDDEN'); expect(codeOf(() => registry.review(governor, 'VIEW-404', 'Query review confirms metric provenance, field restrictions, query costs, and consumer access limits.'))).toBe('NOT_FOUND'); expect(codeOf(() => registry.publish(operator, input.id))).toBe('CONFLICT'); expect(codeOf(() => registry.review(governor, input.id, 'brief'))).toBe('VALIDATION'); });
});
